<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="37" started-at="2014-06-16T19:14:16Z" finished-at="2014-06-16T19:14:16Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="37" started-at="2014-06-16T19:14:16Z" finished-at="2014-06-16T19:14:16Z">
      <class name="Metrics.NewTest">
        <test-method status="PASS" signature="f()[pri:0, instance:Metrics.NewTest@de0a01f]" name="f" duration-ms="15" started-at="2014-06-16T13:14:16Z" finished-at="2014-06-16T13:14:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="FAIL" signature="f2()[pri:0, instance:Metrics.NewTest@de0a01f]" name="f2" duration-ms="2" started-at="2014-06-16T13:14:16Z" finished-at="2014-06-16T13:14:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Fail] but found [Shane]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Fail] but found [Shane]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Metrics.NewTest.f2(NewTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f2 -->
      </class> <!-- Metrics.NewTest -->
      <class name="Metrics.NewTest2">
        <test-method status="PASS" signature="f()[pri:0, instance:Metrics.NewTest2@66133adc]" name="f" duration-ms="2" started-at="2014-06-16T13:14:16Z" finished-at="2014-06-16T13:14:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- Metrics.NewTest2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
